apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: django
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: django-app
  namespace: django
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: django-app
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: django
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx