apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: django
data:
  nginx.conf: |
    upstream hello_django {
        server django-app:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://hello_django;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
            client_max_body_size 100M;
        }

        location /static/ {
            alias /home/app/web/staticfiles/;
        }

        location /media/ {
            alias /home/app/web/mediafiles/;
        }
    }
