pipeline{
    agent any
    environment {
        MAVEN_HOME = '/usr/local/Cellar/maven/3.9.8/bin'
        PATH = "${MAVEN_HOME}:${env.PATH}"
    }
    stages{
        stage('Fetch code'){
            steps{
                git branch: 'paac', url: 'https://github.com/devopshydclub/vprofile-project.git'
            }
        }
        stage('Build'){
            steps{
                sh 'mvn install'
            }
        }
        stage('Test'){
            steps{
                sh 'mvn test'
            }
        }
    }
}